## Include correct information about the app and key details
consumer_key: 
consumer_secret: 
access_token: 
access_secret: 
migration_url: https://developer.api.intuit.com/v2/oauth2/tokens/migrate
accounting_base_url: https://quickbooks.api.intuit.com/
oauth2_client_id: 
oauth2_client_secret: 
redirect_uri: https://developer.intuit.com/v2/OAuth2Playground/RedirectUrl